FROM proget.inedo.com/productimages/inedo/proget:25.0.14@sha256:d906ed525386aeec9fdf4b58049bf67556ec0e912b0204d312662d2b5c35aebc

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"
