FROM proget.inedo.com/productimages/inedo/proget:23.0.22@sha256:2e9822ca410ae160cccef8db3bbd181c5c2cb804ce703dac636229d3b4be0421

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"
