FROM proget.inedo.com/productimages/inedo/proget:23.0.8@sha256:b0b530d63b5b00ea706e554dda5c2c281e7feeef75eb7def0bce963faa662eb8

LABEL maintainer="Michael Kriese <michael.kriese@visualon.de>" \
    name="proget" \
    org.opencontainers.image.source="https://my.inedo.com/proget/versions" \
    org.opencontainers.image.url="https://inedo.com/proget"
